### PR TITLE
Fix on elasticsearch 5.x

### LINKED ISSUE #13: Error on ES 5.x
With ElasticSearch 5.x, the backup fails, because the parameter "wait for completion" is only valid for creating or restoring a snapshot. When using it with -XGET or -XDELETE, the following error is shown:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_snapshot/dsb___GLOBAL__/dump] contains unrecognized parameter: [wait_for_completion]"}],"type":"illegal_argument_exception","reason":"request [/_snapshot/dsb___GLOBAL__/dump] contains unrecognized parameter: [wait_for_completion]"},"status":400}`

### PR DESCRIPTION
**Pull request by Phygon**
Removed wait_for_completion for -XGET and -XDELETE request. This fixes #13.

### CODE REVIEW

**Comment by kiorky** [comment]
Ok for the idea, but not for the current implementation proposal, check for the error, and if not supported fallback to not use wait_for_completion which is legit in newer versions.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#snapshots-take-snapshot

**Comment by kiorky** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/modules-snapshots.html#_snapshot


also on 5.x, the problem is maybe the verb, add -XPUT !

**Comment by kiorky** [comment]
I think the pb is on the delete method, i removed the parameter here, please retry with master

**Comment by Phygon** [comment]
The problem is with GET **and** DELETE. I tested removing wait_for_completion only on the DELETE, but then the GET shows the same error.

**Comment by Phygon** [comment]
From the docs, only the snapshot (PUT) and restore APIs support wait_for_completion, but it is not specified for GET or DELETE:
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-snapshots.html#monitor-snapshot-restore-progress

It seems that 2.4 ignores the unsupported parameter, while 5.x throws an error.

**Comment by kiorky** [comment]
Ok, retry with last master :)

**Comment by Phygon** [comment]
It's working now. Thanks for "merging"!

**Comment by kiorky** [comment]
No problem, Have fun !

**Pull request closed without merging**
